title: Chris Willingham
description: My Personal Blog
author: Chris Willingham
logo: /static/img/profile-photo.jpg
github: https://github.com/clwillingham
about: Secret Ninja
disqus_shortname: clwillingham
#google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: 'http://www.slideshare.net/ChrisWillingham1/2015resumechriswillinghamnocontactinfo-50776514'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/clwillingham
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      
social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://localhost:5000/"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
